### ISSUE TITLE
change cursor

### ISSUE THREAD

**Issue by sina-yeganeh** [replit/kaboom#169]
Hello again!
Can I change mouse cursor in kaboom?

I try this code in CSS but It's not working for me:
```css
body {
  overflow: hidden;
  margin: 0;
  cursor: url("new-cursor.ico"), default;
}
```

what I must do?
